### ISSUE TITLE
crashed in Harmony Next Emulator API 11 x86_64

### ISSUE THREAD

**Issue by Amarterlus** [Tencent/MMKV#1278] opened 2024-04-25 01:13 UTC
![Snipaste_2024-04-25_16-51-29](https://github.com/Tencent/MMKV/assets/18757062/4cb316b0-f347-4305-a974-c75c56de05fa)

[IDE INFO]
DevEco Studio NEXT Developer Preview2
Build Version: 4.1.3.700, built on March 19, 2024
[crash2.log](https://github.com/Tencent/MMKV/files/15106965/crash2.log)

**Comment by lingol** [comment] 2024-04-25 04:15
I don't see any mmkv related symbols or so in your crash log. 

What's the log from hilog?

**Comment by Amarterlus** [comment] 2024-04-25 08:53
> I don't see any mmkv related symbols or libmmkv.so in your crash log.
> 
> What's the log from hilog?



> I don't see any mmkv related symbols or libmmkv.so in your crash log.
> 
> What's the log from hilog?

**Comment by lingol** [comment] 2024-04-25 10:38
>04-25 16:50:31.066  2458  2458 I A00000/MMKV: <native_bridge.cpp:83::NValueToString> NAPI Error: code 1, msg Invalid parameter
>04-25 16:50:31.066  2458  2458 E C03f00/ArkCompiler: [ecmascript] Pending exception before ToString called in line:242, exception details as follows:
>04-25 16:50:31.066  2458  2458 E C03f00/ArkCompiler: Error: null
>04-25 16:50:31.066  2458  2458 E C03f00/ArkCompiler:     at initializeWithPath (oh_modules/.ohpm/@tencent+mmkv@1.3.5/oh_modules/@tencent/mmkv/src/main/ets/utils/MMKV.ets:54:26)

When you called `MMKV.initialize()` (or `MMKV.initializeWithPath()`), what param did you pass as `context` (or `rootDir` & `cacheDir`)? Did you accedently pass `null` or `undefined`?

**Comment by Amarterlus** [comment] 2024-04-26 01:18
at EntryAbility onCreate(want: Want, launchParam: AbilityConstant.LaunchParam)
something like 
const filePath: string = context.filesDir + "/mmkv"
const cachePath: string = context.cacheDir + "/mmkv"
MMKV.initializeWithPath(filePath, cachePath)

**Comment by lingol** [comment] 2024-04-26 02:12
Would you print the `filePath, cachePath` before calling `MMKV.initializeWithPath()`?

**Comment by Amarterlus** [comment] 2024-04-26 06:44
> Would you print the `filePath, cachePath` before calling `MMKV.initializeWithPath()`?

path is leagl 
filePath => /data/storage/el2/base/haps/entry/files/mmkv 
cachePath => /data/storage/el2/base/haps/entry/cache/mmkv

**Comment by lingol** [comment] 2024-04-26 07:49
That's strange. Can you provide a reproducible demo project?

**Comment by Amarterlus** [comment] 2024-04-26 16:33
> That's strange. Can you provide a reproducible demo project?

actually I just create a new project with empty Ability 
maybe IDE version or emulator version not suit 
but change to @ohos/mmkv dose work

**Comment by lingol** [comment] 2024-04-27 05:13
Does it work if you passed in an Application Context?

**Comment by Amarterlus** [comment] 2024-04-28 01:18
> Does it work if you passed in an Application Context?

just same fatal error

**Comment by lingol** [comment] 2024-04-28 03:08
We can't reproduce this in a device. Did you only reproduce this in a simulator?

**Comment by lingol** [comment] 2024-04-28 03:15
I just found out that you are using DevEco Studio 4.1.3.700, you should try using the 5.0.3.100 or newer.

**Comment by lingol** [comment] 2024-04-28 03:24
Aka, @tencent/mmkv is developed under 5.0.3.100 (API 12). We have not tested our lib under API 11. 
I am not surprised it doesn't run correctly.

**Comment by ChawLoo** [comment] 2024-04-28 04:03
目前测试情况如下：
Dev：5.0.3.200
模拟器：Beta1（正常），Preview2（报错）
真机：Preview2（正常）

**Comment by lingol** [comment] 2024-04-28 04:34
Okay, I think we can close this issue for now, for Beta1 is newer than Preview2 if I understand correctly.

**Closed by lingol** 2024-04-28 04:34 UTC
