### ISSUE TITLE
最新版本1.3.5

### ISSUE THREAD

**Issue by minorlai** [Tencent/MMKV#1338] opened 2024-07-05 02:44 UTC
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

Kotlin

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

v1.3.5

### The platform of MMKV

> e.g. iOS or Android

Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

步骤：application oncreate 初始化mmkv后，在SplashActivity使用mmkv，出现以下错误:
Fatal Exception: java.lang.UnsatisfiedLinkError
dlopen failed: library "libmmkv.so" not found
java.lang.Runtime.loadLibrary0 (Runtime.java:1077)

java.lang.System.loadLibrary (System.java:1656)
com.tencent.mmkv.MMKV.doInitialize (MMKV.java:223)
com.tencent.mmkv.MMKV.initialize (MMKV.java:205)
com.tencent.mmkv.MMKV.initialize (MMKV.java:91)
com.talk.inapp.app.TalkInApp.initCache (TalkInApp.kt:90)
com.talk.inapp.app.TalkInApp.onCreate (TalkInApp.kt:54)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1223)

com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1009)

原本使用1.3.2的版本不会出现这个错误，更新后出现的

**Comment by lingol** [comment] 2024-07-05 02:54
Your case is complicated. Please provide a reproducible demo project.

**Comment by jzlhll** [comment] 2024-07-06 01:30
1.3.5+ drop x86 and armV7.

**Comment by lingol** [comment] 2024-07-06 05:24
> 1.3.5+ drop x86 and armV7.
That's a possible reason. 
You can verify that by upgrading just to v1.3.4 and check if it crashes or not.

**Comment by lingol** [comment] 2024-07-08 09:49
[v1.3.7 LST](https://github.com/Tencent/MMKV/releases/tag/v1.3.7 ) has just been release.

**This Long Term Support (LTS) release** primarily reintroduces support for the ARMv7 architecture and lowers the minimum SDK version requirement to 21. Please note that only critical bug fixes will be applied to the 1.3.x series. 

New features will be introduced in version 2.0 and later, which will discontinue support for 32-bit architectures and raise the minimum SDK version requirement to 23.

**Closed by lingol** 2024-07-08 09:49 UTC

**Comment by minorlai** [comment] 2024-07-19 01:49
更新至 1.3.7的版本后，依然存在闪退问题
![image](https://github.com/user-attachments/assets/1bea6f38-7023-4e2f-b0ea-fc169cf9ba23)

**Comment by lingol** [comment] 2024-07-19 02:00
@minorlai Have you looked at your crash carefully? Yours is a totally different issue, **misusing armv7 for arm64**.
<img width="301" alt="image" src="https://github.com/user-attachments/assets/f8d0a26e-ee72-4888-af38-680e3b0286e7">

**Comment by minorlai** [comment] 2024-07-21 02:47
> @minorlai Have you looked at your crash carefully? Yours is a totally different issue, **misusing armv7 for arm64**. <img alt="image" width="301" src="https://private-user-images.githubusercontent.com/2088859/350199035-f8d0a26e-ee72-4888-af38-680e3b0286e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MzAyODcsIm5iZiI6MTcyMTUyOTk4NywicGF0aCI6Ii8yMDg4ODU5LzM1MDE5OTAzNS1mOGQwYTI2ZS1lZTcyLTQ4ODgtYWYzOC02ODBlM2IwMjg2ZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjFUMDI0NjI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDg0ODc4ZTdhNWNiODlkNTdmZGFkNGUzYWRiOTIzYWJlZTJhMzUwYzFmNWZiNWYwYWY5ZDE2OWQyZmJkMjg3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.77mtodTN67saXkI53NWU111NVIcNz363UjkZJtmr9Rk">

gradle配置：
` ndk {
            abiFilters "arm64-v8a","armeabi-v7a"
        }`
错误是线上用户统计到的，自己的设备没办法复现

**Comment by lingol** [comment] 2024-07-21 05:22
Have you tried ReLinker as the FAQ suggested?

**Comment by minorlai** [comment] 2024-07-21 07:35
没有尝试其他，请问我该如何调整呢？针对的线上用户都是海外用户，是否海外机型兼容方面会不一样？

**Comment by lingol** [comment] 2024-07-21 11:55
> @lingol 
> 
> 没有尝试其他，请问我该如何调整呢？针对的线上用户都是海外用户，是否海外机型兼容方面会不一样？
> 

I thought I just said, follow the FAQ.

**Comment by minorlai** [comment] 2024-07-23 01:26
> > @lingol
> > 没有尝试其他，请问我该如何调整呢？针对的线上用户都是海外用户，是否海外机型兼容方面会不一样？
> 
> I thought I just said, follow the FAQ.

我退回 1.3.4的版本，再观察问题

**Comment by minorlai** [comment] 2024-08-04 02:21
@lingol 已经升级1.3.9，试了1.3.4/1.3.5/1.3.7/1.3.9 多个版本，依然出现错误
![image](https://github.com/user-attachments/assets/2ca5cefb-01be-4319-8031-71ef32bb2e8a)
项目配置的ndk是 
`ndk {
            abiFilters "arm64-v8a","armeabi-v7a"
        }`

**Comment by lingol** [comment] 2024-08-04 03:45
> Have you tried ReLinker as the FAQ suggested?

**Comment by minorlai** [comment] 2024-08-07 02:25
> > Have you tried ReLinker as the FAQ suggested?

已经尝试Relinker 库去做兼容，但是出现另一个错误
![image](https://github.com/user-attachments/assets/fda4cae0-63e5-4bb3-b571-096bd7f47e2d)

**Comment by lingol** [comment] 2024-08-07 04:15
OK, now looks like something is wrong with your package. In your original issue you mention that this problem occurs when you **upgrade from v1.3.2.** Are there **other changes** along side with the upgrade of MMKV that you have failed to notice that cause this problem?
To verify that, you can try this: **downgrade MMKV to v1.3.2** with other changes (including ReLinker) **untouched**, and see if the problem still exists.
If the problem still exists, then it's not the MMKV upgrade that caused the problem, it's other changes you or your team made cause it.

**Comment by minorlai** [comment] 2024-08-18 02:45
> OK, now looks like something is wrong with your package. The libmmkv.so is absolutely missing in the APK/Android App Bundles.
> 
> In your original issue you mention that this problem occurs when you **upgrade from v1.3.2.** Are there **other changes on the project** along side with the upgrade of MMKV that you have failed to notice that cause this problem? To verify that, you can try this: **downgrade MMKV to v1.3.2** with other changes (including ReLinker) **untouched**, and see if the problem still exists. If the problem still exists, then it's not the MMKV upgrade that caused the problem, it's other changes you or your team made cause it.

你好，我把版本退回1.3.2/1.3.4 依然出现错误，而且影响的用户人数更多了，错误如下：
![image](https://github.com/user-attachments/assets/3868bfe1-a9e6-44c9-9b76-9c7f470e80de)

**Comment by lingol** [comment] 2024-08-18 03:04
And it's confirmed that it is not a MMKV issue but something else you or your team have done that caused the problem.

**Comment by minorlai** [comment] 2024-08-18 03:34
你好，根据异常日志 ` Could not find 'libmmkv.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: []. `，的确是因为无法找到`` libmmkv.so 导致的

**Comment by lingol** [comment] 2024-08-18 03:59
If you can't understand the logic behind downgrading to your original version to narrow down the cause, think about it again. 

I should lock this issue for any unnecessary bias.
