### ISSUE TITLE
ActualSize much less than real file size.

### ISSUE THREAD

**Issue by alhah** [Tencent/MMKV#86] opened 2018-10-16 13:31 UTC
### The language of MMKV
Java

### The version of MMKV
v1.0.10

### The platform of MMKV
Android

### What's the issue?
OOM caused by mmkv file size too large.
loading [***] with file size 134217728, oldActualSize 6788724, newActualSize 6788839

Only 1000+ key-values occupies 130M. 
What's the possible reason for actualSize much less than file size, multi-process read & write in single process mode?

**Comment by lingol** [comment] 2018-10-16 13:45
It's possible. It's not about how many items you store, but how big your items are.

**Comment by alhah** [comment] 2018-10-16 13:48
Should actualSize equals file size?

**Comment by lingol** [comment] 2018-10-16 14:11
No.

**Comment by alhah** [comment] 2018-10-17 04:08
Thank you. We didn't stored big date.
I check the big mmkv file with hex friend, only first 4M is valid data, remaining 130M is "0".

**Comment by lingol** [comment] 2018-10-17 06:31
That's wired. Can you send a reproducible demo project to me? guoling@tencent.com

**Comment by alhah** [comment] 2018-10-17 06:52
I don't know the reproduce step, I got the file from online gray version.

The first line is like this, the actual size is same with valid data size.
69B93F00 A6DE021C 31303634 32373733 37396C61 73745F75

The last line is like this, which means “ "mRealTime":false}] ”, seems like the end of a string set.
226D5265 616C5469 6D65223A 66616C73 657D5D00 0000

I am checking the value size key by key.

**Comment by lingol** [comment] 2018-10-17 07:42
By the way, why are you using `MULTI_PROCESS_MODE` in a single process App?

**Comment by lingol** [comment] 2018-10-17 08:27
Json is just a String, nothing special. Is there any change that there're some big items stored in MMKV and deleted afterward?

**Comment by alhah** [comment] 2018-10-17 08:32
I am not very sure of that, need further check, what's the exact definition of "big"?

**Comment by lingol** [comment] 2018-10-17 08:41
Items with size of 10K+ is consider big.

**Comment by alhah** [comment] 2018-10-17 09:31
Do you mean remove big items would not trigger file resize?
I add some log in MiniPBCoder::decodeOneMap:
{
    int i = 0;
    int j = 0;
    while (!m_inputData->isAtEnd()) {
        const auto &key = m_inputData->readString();
        if (key.length() > 0) {
          i++;
          auto value = m_inputData->readData();
            if (value.length() > 0) {
              j += value.length();
                dic[key] = move(value);
            } else {
                dic.erase(key);
            }
        }
    }
  MMKVInfo("total %d keys, value size %d", i, j);
}
loading [***] with 4176233 size in total, file size is 134217728
loading [***] with crc 4170586551 sequence 4
total 3412 keys, value size 4081561
loaded [***] with 1111 values

**Comment by alhah** [comment] 2018-10-17 13:07
I think I have found the reason, the futureUsage is over estimated:
size_t futureUsage = newSize * std::max<size_t>(8, (m_dic.size() + 1) / 2);

My last value size is 130K, m_dic.size() is 1000+, then the file will resize to 130M, but most of it will never been used.

This means, if I store thousands of keys in a file, it will very easy to cause OOM.

**Comment by lingol** [comment] 2018-10-17 13:15
Oh I see...Let me think about that.

**Comment by lingol** [comment] 2018-10-22 09:21
Fixed with this [commit](https://github.com/Tencent/MMKV/commit/b8f5911415f9338765174993f7631448dcc65ab1).

**Comment by alhah** [comment] 2018-10-22 11:05
I think it's good enough for me, thank you. How far will this release?

By the way, I found there is no reduce file size operation except "clearAll", if I store a lot of key-values in one file and then delete most of them in some time, it seems will waste some disk space.

Should I avoid this kind of usage as far as possible?

**Comment by lingol** [comment] 2018-10-22 12:18
That's a good suggestion. A `trim` operation should be supported.

**Comment by alhah** [comment] 2018-10-22 12:53
Waiting for good news, thank you very much!

**Comment by alhah** [comment] 2018-11-14 07:43
Wonderful!

**Comment by alhah** [comment] 2018-11-20 14:03
It seems [use average item size to calc future usage](https://github.com/Tencent/MMKV/commit/b8f5911415f9338765174993f7631448dcc65ab1) does not merge into android code.

**Comment by lingol** [comment] 2018-11-20 14:45
> It seems [use average item size to calc future usage](https://github.com/Tencent/MMKV/commit/b8f5911415f9338765174993f7631448dcc65ab1) does not merge into android code.

I can't believe these, looks like there's a mistake on my local git repo.
Will fix soon.

**Comment by lingol** [comment] 2018-11-21 02:58
Fixed with this [commit](https://github.com/Tencent/MMKV/commit/ddbbc61339fe76f5f2bbffae752cef322d304d52). But A new version will likely come out next week.

**Comment by lingol** [comment] 2018-11-30 09:47
Released with [v1.0.14](https://github.com/Tencent/MMKV/releases/tag/v1.0.14).

**Closed by lingol** 2018-11-30 09:47 UTC
