### ISSUE TITLE
Crash at file crc32_armv8.cpp: mmkv::armv8_crc32(unsigned int, unsigned char const*, unsigned long)

### ISSUE THREAD

**Issue by leishuai** [Tencent/MMKV#525] opened 2020-09-08 05:32 UTC
### The language of MMKV
> Objective-C

### The version of MMKV

> v1.1.1

### The platform of MMKV

>  iOS, only iOS 13.

### The installation of MMKV

>  Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> crash on iOS

### What's the log of MMKV when that happened?
EXC_BAD_INSTRUCTION

0 XX mmkv::armv8_crc32(unsigned int, unsigned char const*, unsigned long) (in XX) crc32_armv8.cpp:79
1 XX mmkv::MMKV::recaculateCRCDigestWithIV(void const*) (in XX) MMKV.cpp:990
2 XX mmkv::MMKV::doFullWriteBack(mmkv::MMBuffer&&) (in XX) MMKV.cpp:884
3 XX mmkv::MMKV::ensureMemorySize(unsigned long) (in XX) MMKV.cpp:630
4 XX mmkv::MMKV::appendDataWithKey(mmkv::MMBuffer const&, NSString*) (in XX) MMKV.cpp:781
5 XX mmkv::MMKV::setDataForKey(mmkv::MMBuffer&&, NSString*) (in XX) MMKV.cpp:735
6 XX mmkv::MMKV::set(bool, NSString*) (in XX) MMKV.cpp:1015
7 XX -[MMKV setBool:forKey:] (in XX) libMMKV.mm:292
8 XX -[KnTabBarController hideReviewTipViewIfNeed] (in XX) KnTabBarController.m:163
9 libdispatch.dylib __dispatch_client_callout (in libdispatch.dylib)
10 libdispatch.dylib __dispatch_continuation_pop$VARIANT$mp (in libdispatch.dylib)
11 libdispatch.dylib __dispatch_source_invoke$VARIANT$mp (in libdispatch.dylib)
12 libdispatch.dylib __dispatch_main_queue_callback_4CF$VARIANT$mp (in libdispatch.dylib)
13 CoreFoundation ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ (in CoreFoundation)
14 CoreFoundation ___CFRunLoopRun (in CoreFoundation)
15 CoreFoundation _CFRunLoopRunSpecific (in CoreFoundation)
16 GraphicsServices _GSEventRunModal (in GraphicsServices)
17 UIKitCore _UIApplicationMain (in UIKitCore)
18 XoaInfoPlug1.dylib ((null))
19  main (in XX) main.m:13
20 libdyld.dylib _start (in libdyld.dylib)

**Comment by leishuai** [comment] 2020-09-08 08:49
all on HongKong Version iPhone

**Comment by lingol** [comment] 2020-09-08 13:02
Have you try upgrading to the latest version v1.2.2 and try again?

**Comment by leishuai** [comment] 2020-09-09 03:26
Yeah, I've tried.   1.2.2 still crash, only on not mainland device(非国行)。

crash at mmkv::armv8_crc32(unsigned int, unsigned char const*, unsigned long) (in openlanguage) crc32_armv8.cpp:98.

Is there any way to avoid this crash by now? It affects large scale of app users.

**Comment by lingol** [comment] 2020-09-09 05:45
Any logs from mmkv?

**Comment by leishuai** [comment] 2020-09-09 06:59
No MMKV logs.   Only crash log.   What do you think the reason is?

**Comment by lingol** [comment] 2020-09-09 07:44
No ideas for now. It's better to have mmks logs. Do you have one of those HK models?

**Comment by leishuai** [comment] 2020-09-09 10:48
How do I get mmkv logs?
For now I can't have HK model which can reproduce the issue.

EXC_BAD_INSTRUCTION, do u think it's arch problem?

**Comment by lingol** [comment] 2020-09-09 17:32
https://github.com/Tencent/MMKV/wiki/iOS_advance#log

**Comment by lingol** [comment] 2020-09-10 11:25
I have tried to fix this crash on the dev branch. But I'm not sure about that. Can you try it out? https://github.com/Tencent/MMKV/commit/1f1fba899bf417b82e8af6d8b6a6b74671225254

**Comment by leishuai** [comment] 2020-09-16 10:50
Thanks for your reply, my dear friend.

**Comment by hllGitHub** [comment] 2020-09-17 09:23
I'll have a try, thanks

**Comment by lingol** [comment] 2020-09-23 05:46
Hey, guys. How does it go? Does it fix the issue yet? @leishuai @hllGitHub @hakoapp @yunjinghui123

**Comment by yunjinghui123** [comment] 2020-09-24 08:08
This problem only showed a large number of user crash records on 9.11, but there was no crash after 9.11. I don’t know what caused it, and it can’t be verified.

**Comment by yuhanle** [comment] 2020-09-28 11:53
> I'll have a try, thanks

Is there any improvement?

**Comment by hllGitHub** [comment] 2020-10-05 02:21
It hasn't improved significantly.

**Comment by lingol** [comment] 2020-10-13 09:19
Fixed with commit https://github.com/Tencent/MMKV/commit/093f9efc2ec4ea4d6e8641838b0baebccc7d4ca4.

**Comment by lingol** [comment] 2020-10-16 14:21
Released with [v1.2.3](https://github.com/Tencent/MMKV/releases/tag/v1.2.3).

**Closed by lingol** 2020-10-16 14:21 UTC
Labels: help wanted

**Comment by yuhanle** [comment] 2020-10-20 05:47
> Released with [v1.2.3](https://github.com/Tencent/MMKV/releases/tag/v1.2.3).

Is there a specific reason for the crash? How can i reproduce

**Comment by lingol** [comment] 2020-10-20 05:51
> > Released with [v1.2.3](https://github.com/Tencent/MMKV/releases/tag/v1.2.3).
> 
> Is there a specific reason for the crash? How can i reproduce

I myself can't reproduce this crash. The solution is to turn off crc32 instructions and use iOS system-provided zlib instead. That will avoid the crash from the top.
