### ISSUE TITLE
[Android]MMKVRecoverStrategic not work after the main process crash.

### ISSUE THREAD

**Issue by upsidedown0991** [Tencent/MMKV#755] opened 2021-09-06 03:03 UTC
## Note:
Background: 
We have some users who report the configuration is missing.
Then we try to simulate by killing the app serval times & writing a value every 500  ms.

Result:
lost all configuration even if add MMKVHandler  

[recover-from-data-corruption](https://github.com/Tencent/MMKV/wiki/android_advance#recover-from-data-corruption)
Get MMKV instance by MMKV.SINGLE_PROCESS_MODE

### The language of MMKV

Kotlin

### The version of MMKV

 v1.2.10  

### The platform of MMKV

Android

### The installation of MMKV

gradle 
implementation("com.tencent:mmkv-static:1.2.10")

### What's the issue?
Step1: 

```
            val root = MMKV.initialize(app)

            MMKV.registerHandler(object : MMKVHandler {
                override fun onMMKVCRCCheckFail(mmapID: String?): MMKVRecoverStrategic {

                    Utils.log("haha mmkv error onMMKVCRCCheckFail ${mmapID}")
                    return MMKVRecoverStrategic.OnErrorRecover
                }

                override fun onMMKVFileLengthError(mmapID: String?): MMKVRecoverStrategic {
                    Utils.log("haha mmkv error onMMKVFileLengthError ${mmapID}")
                    return MMKVRecoverStrategic.OnErrorRecover
                }

                override fun wantLogRedirecting(): Boolean {
                    return false
                }

                override fun mmkvLog(
                    level: MMKVLogLevel?,
                    file: String?,
                    line: Int,
                    function: String?,
                    message: String?
                ) {
                }

            })
```
Step 2:
```
        Observable.interval(500,TimeUnit.MILLISECONDS)
            .observeOn(Schedulers.io())
            .subscribeOn(AndroidSchedulers.mainThread())
            .subscribe({
                val value = SPUtils.getLong("test_mmkv",0L)
                Utils.log("haha mmkv  ${it} read = ${value}")
                SPUtils.setLong("test_mmkv",(it + value))
            },{

            })
```
Step 3:
```
adb shell am force-stop packageName
```

Finally, we will take more time to test MMKV.MULTI_PROCESS_MODE ,which seems to work great right now.

Any suggestions by MMKV.SINGLE_PROCESS_MODE?

Thanks

**Comment by lingol** [comment] 2021-09-06 03:20
> Any suggestions by MMKV.SINGLE_PROCESS_MODE?

If you use an MMKV instance by multi-process, you must set `MMKV.MULTI_PROCESS_MODE`, like wise use `MMKV. SINGLE_PROCESS_MODE` if you only use that instance in one process.

As for MMKV's recovery logic, it doesn't promise a full recovery under any conditions. And it's not affected by process mode.

**Comment by upsidedown0991** [comment] 2021-09-06 03:28
I think we are inited/get/set only in the main thread.
and we don't know there is recovery is runing&ending, right?

**Comment by lingol** [comment] 2021-09-06 03:33
Trust, but verify.

**Comment by lingol** [comment] 2021-09-06 03:34
>and we don't know there is recovery is runing&ending, right?

You do know that by receiving callbacks from MMKVHandler you registered.

**Comment by upsidedown0991** [comment] 2021-09-06 03:40
> > and we don't know there is recovery is runing&ending, right?
> 
> You do know that by receiving callbacks from MMKVHandler you registered.

It seems the callback did not work in v1.2.10 ,which  console print nothing

**Comment by lingol** [comment] 2021-09-06 03:42
Then recovery is not running. Why do you think the problem is due to recovery? Do you have **logs of MMKV** to suggest that?

**Comment by upsidedown0991** [comment] 2021-09-06 04:00
> Then recovery is not running. Why do you think the problem is due to recovery? Do you have **logs of MMKV** to suggest that?

Yes. the log is here.  the issue is we want to report  callback didn't trigger. 



```
2021-09-06 11:54:02.422 11325-11325 E/UtilsLog: MMKV LOG <MMKV_IO.cpp:81::loadFromFile> loading [testMMKV] with 0 actual size, file size 4096, InterProcess 0, meta info version:0
2021-09-06 11:54:02.422 11325-11325 E/UtilsLog: MMKV LOG <MMKV_IO.cpp:130::loadFromFile> loaded [testMMKV] with 0 key-values
2021-09-06 11:54:03.574 11409-11409 E/UtilsLog: MMKV LOG <MMKV_IO.cpp:81::loadFromFile> loading [testMMKV] with 16 actual size, file size 4096, InterProcess 0, meta info version:3
2021-09-06 11:54:03.574 11409-11409 E/UtilsLog: MMKV LOG <MMKV_IO.cpp:86::loadFromFile> loading [testMMKV] with crc 534749736 sequence 1 version 3
2021-09-06 11:54:03.574 11409-11409 E/UtilsLog: MMKV LOG <MMKV_IO.cpp:130::loadFromFile> loaded [testMMKV] with 1 key-values
2021-09-06 11:54:22.800 11976-11976 E/UtilsLog: MMKV LOG <MMKV.cpp:382::checkFileCRCValid> check crc [testMMKV] fail, crc32:3029484855, m_crcDigest:2840591979
2021-09-06 11:54:22.800 11976-11976 E/UtilsLog: MMKV LOG <MMKV_IO.cpp:81::loadFromFile> loading [testMMKV] with 4 actual size, file size 4096, InterProcess 0, meta info version:3
2021-09-06 11:54:22.800 11976-11976 E/UtilsLog: MMKV LOG <MMKV_IO.cpp:86::loadFromFile> loading [testMMKV] with crc 1285129681 sequence 1 version 3
2021-09-06 11:54:22.800 11976-11976 E/UtilsLog: MMKV LOG <MMKV_IO.cpp:130::loadFromFile> loaded [testMMKV] with 0 key-values
2021-09-06 11:54:24.039 12109-12109 E/UtilsLog: MMKV LOG <MMKV_IO.cpp:81::loadFromFile> loading [testMMKV] with 16 actual size, file size 4096, InterProcess 0, meta info version:3
2021-09-06 11:54:24.039 12109-12109 E/UtilsLog: MMKV LOG <MMKV_IO.cpp:86::loadFromFile> loading [testMMKV] with crc 534749736 sequence 2 version 3
2021-09-06 11:54:24.039 12109-12109 E/UtilsLog: MMKV LOG <MMKV_IO.cpp:130::loadFromFile> loaded [testMMKV] with 1 key-values
```

**Comment by lingol** [comment] 2021-09-06 04:03
Got it. Will look into this later.

**Comment by lingol** [comment] 2021-09-08 12:36
Sorry, but I can't reproduce your issue about `MMKVHandler` not being called. In my local demo project, it's always been called when there's a CRC error or file length error.
So I take a second look at your example code and find something funny.
>            val root = MMKV.initialize(app)

Where exactly did you call this line (and other lines follow) in your step 1? A normal init call should be put inside your `Application` class's override `OnCreate()` function. And in that function, one should only pass `this` to `MMKV.initialize()`. Yet you pass some variable called `app`.

**Comment by upsidedown0991** [comment] 2021-09-10 08:41
Yep.it's weird. we are calling `MMKV.initialize(app)` in the Application's `onCreate()` function

**Comment by upsidedown0991** [comment] 2021-09-30 01:33
Sorry. Not yet. But Get MMKV by MULTI_PROCESS_MODE will be OK that won't lose the data.

**Comment by lingol** [comment] 2021-09-30 02:51
You should dig deeper. 
Chance are you are **mistakenly** using MMKV in multiple processes. 
Or, worse than that, you have **mistakenly created another process without knowing** it. If I were you, I won't sleep on it.

Anyway, looks like it's not MMKV's fault. I'm closing this issue.

**Closed by lingol** 2021-09-30 02:51 UTC
